//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeJPGToPDFConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeJPGToPDFConverter.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subdirectories ?.
        /// </summary>
        internal static string Add_Subdirectories__ {
            get {
                return ResourceManager.GetString("Add Subdirectories ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want clear the added files ?.
        /// </summary>
        internal static string Are_you_sure_that_you_want_clear_the_added_files__ {
            get {
                return ResourceManager.GetString("Are you sure that you want clear the added files ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Margin.
        /// </summary>
        internal static string Big_Margin {
            get {
                return ResourceManager.GetString("Big Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string Bottom_Center {
            get {
                return ResourceManager.GetString("Bottom Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string Bottom_Left {
            get {
                return ResourceManager.GetString("Bottom Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string Bottom_Right {
            get {
                return ResourceManager.GetString("Bottom Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDF Properties.
        /// </summary>
        internal static string Change_PDF_Properties {
            get {
                return ResourceManager.GetString("Change PDF Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Added Files ?.
        /// </summary>
        internal static string Clear_Added_Files__ {
            get {
                return ResourceManager.GetString("Clear Added Files ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ! Image does not exist !.
        /// </summary>
        internal static string Error___Image_does_not_exist__ {
            get {
                return ResourceManager.GetString("Error ! Image does not exist !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not run new Setup File !.
        /// </summary>
        internal static string Error__Could_not_run_new_Setup_File__ {
            get {
                return ResourceManager.GetString("Error. Could not run new Setup File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not specify if Application will start automatically with Windows.
        /// </summary>
        internal static string Error__Could_not_specify_if_Application_will_start_automatically_with_Windows {
            get {
                return ResourceManager.GetString("Error. Could not specify if Application will start automatically with Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. File or Directory not found !.
        /// </summary>
        internal static string Error__File_or_Directory_not_found__ {
            get {
                return ResourceManager.GetString("Error. File or Directory not found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not parse Arguments !.
        /// </summary>
        internal static string Error_could_not_parse_Arguments__ {
            get {
                return ResourceManager.GetString("Error could not parse Arguments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not read file !.
        /// </summary>
        internal static string Error_could_not_read_file__ {
            get {
                return ResourceManager.GetString("Error could not read file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not start log writer !.
        /// </summary>
        internal static string Error_could_not_start_log_writer__ {
            get {
                return ResourceManager.GetString("Error could not start log writer !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing List !.
        /// </summary>
        internal static string Error_while_processing_List__ {
            get {
                return ResourceManager.GetString("Error while processing List !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error wrong file type !.
        /// </summary>
        internal static string Error_wrong_file_type__ {
            get {
                return ResourceManager.GetString("Error wrong file type !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great application to combine !.
        /// </summary>
        internal static string Great_application_to_combine__ {
            get {
                return ResourceManager.GetString("Great application to combine !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great application to convert JPG and other Images to PDF !.
        /// </summary>
        internal static string Great_application_to_convert_JPG_and_other_Images_to_PDF__ {
            get {
                return ResourceManager.GetString("Great application to convert JPG and other Images to PDF !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is From Windows Explorer.
        /// </summary>
        internal static string Is_From_Windows_Explorer {
            get {
                return ResourceManager.GetString("Is From Windows Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to upgrade to the latest version of the application. Press the OK button to download the new version.
        /// </summary>
        internal static string It_is_necessary_to_upgrade_to_the_latest_version_of_the_application__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("It is necessary to upgrade to the latest version of the application. Press the OK" +
                        " button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        internal static string Middle_Center {
            get {
                return ResourceManager.GetString("Middle Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        internal static string Middle_Left {
            get {
                return ResourceManager.GetString("Middle Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        internal static string Middle_Right {
            get {
                return ResourceManager.GetString("Middle Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Margin.
        /// </summary>
        internal static string No_Margin {
            get {
                return ResourceManager.GetString("No Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed.
        /// </summary>
        internal static string Operation_Completed {
            get {
                return ResourceManager.GetString("Operation Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        internal static string Original_Size {
            get {
                return ResourceManager.GetString("Original Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite PDF Document.
        /// </summary>
        internal static string Overwrite_PDF_Document {
            get {
                return ResourceManager.GetString("Overwrite PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add only Word Files !.
        /// </summary>
        internal static string Please_add_only_Word_Files__ {
            get {
                return ResourceManager.GetString("Please add only Word Files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_valid_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a valid Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application !.
        /// </summary>
        internal static string Please_restart_the_application__ {
            get {
                return ResourceManager.GetString("Please restart the application !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an output file !.
        /// </summary>
        internal static string Please_specify_an_output_file__ {
            get {
                return ResourceManager.GetString("Please specify an output file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify another option as the Output Folder !.
        /// </summary>
        internal static string Please_specify_another_option_as_the_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify another option as the Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify at least one image to convert to PDF !.
        /// </summary>
        internal static string Please_specify_at_least_one_image_to_convert_to_PDF__ {
            get {
                return ResourceManager.GetString("Please specify at least one image to convert to PDF !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify at least two Documents to merge !.
        /// </summary>
        internal static string Please_specify_at_least_two_Documents_to_merge__ {
            get {
                return ResourceManager.GetString("Please specify at least two Documents to merge !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify PDF Files to combine !.
        /// </summary>
        internal static string Please_specify_PDF_Files_to_combine__ {
            get {
                return ResourceManager.GetString("Please specify PDF Files to combine !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Folder of PDF Document.
        /// </summary>
        internal static string Same_Folder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Same Folder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Margin.
        /// </summary>
        internal static string Small_Margin {
            get {
                return ResourceManager.GetString("Small Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string Subfolder {
            get {
                return ResourceManager.GetString("Subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of PDF Document.
        /// </summary>
        internal static string Subfolder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Subfolder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit and run the updated setup file.
        /// </summary>
        internal static string The_application_will_now_exit_and_run_the_updated_setup_file {
            get {
                return ResourceManager.GetString("The application will now exit and run the updated setup file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string Top_Center {
            get {
                return ResourceManager.GetString("Top Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string Top_Left {
            get {
                return ResourceManager.GetString("Top Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string Top_Right {
            get {
                return ResourceManager.GetString("Top Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Letter.
        /// </summary>
        internal static string US_Letter {
            get {
                return ResourceManager.GetString("US Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
    }
}
